#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/homes/ugrad/alanachtenberg/Lab3/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /softwares/Linux/xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = /softwares/Linux/xilinx/10.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex5

DEVICE = xc5vlx110tff1136-1

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp /homes/faculty/shared/ECEN449/EDK-XUPV5-LX110T-Pack/lib/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) \
                   $(MICROBLAZE_0_LIBG_OPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error yes

LAB3_OUTPUT_DIR = lab3
LAB3_OUTPUT = $(LAB3_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(LAB3_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(LAB3_OUTPUT) 

ALL_USER_ELF_FILES = $(LAB3_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       microblaze_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = lab3_programclean 

CORE_STATE_DEVELOPMENT_FILES = /softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/proc_common_pkg.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/ipif_pkg.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/or_muxcy.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/or_gate128.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/family_support.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pselect_f.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/counter_f.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_00_a/hdl/vhdl/plb_address_decoder.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_00_a/hdl/vhdl/plb_slave_attachment.vhd \
/softwares/Linux/xilinx/10.1/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_00_a/hdl/vhdl/plbv46_slave_single.vhd \
/homes/ugrad/alanachtenberg/Lab3/pcores/multiply_v1_00_a/hdl/verilog/user_logic.v \
/homes/ugrad/alanachtenberg/Lab3/pcores/multiply_v1_00_a/hdl/vhdl/multiply.vhd

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/debug_module_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/leds_wrapper.ngc \
implementation/inputs_wrapper.ngc \
implementation/multiply_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION LAB3
#################################################################

LAB3_SOURCES = lab3/lab3.c 

LAB3_HEADERS = microblaze_0/include/multiply.h microblaze_0/include/xparameters.h 

LAB3_CC = mb-gcc
LAB3_CC_SIZE = mb-size
LAB3_CC_OPT = -O2
LAB3_CFLAGS = 
LAB3_CC_SEARCH = # -B
LAB3_LIBPATH = -L./microblaze_0/lib/ # -L
LAB3_INCLUDES = -I./microblaze_0/include/  -Imicroblaze_0/include/ # -I
LAB3_LFLAGS = # -l
LAB3_LINKER_SCRIPT = lab3/lab3_linker_script.ld
LAB3_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(LAB3_LINKER_SCRIPT) 
LAB3_CC_DEBUG_FLAG =  -g 
LAB3_CC_PROFILE_FLAG = # -pg
LAB3_CC_GLOBPTR_FLAG= # -mxl-gp-opt
LAB3_MODE = executable
LAB3_LIBG_OPT = -$(LAB3_MODE) microblaze_0
LAB3_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mxl-pattern-compare -mcpu=v7.10.d 
LAB3_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
LAB3_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
LAB3_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
LAB3_OTHER_CC_FLAGS= $(LAB3_CC_GLOBPTR_FLAG)  \
                  $(LAB3_CC_START_ADDR_FLAG) $(LAB3_CC_STACK_SIZE_FLAG) $(LAB3_CC_HEAP_SIZE_FLAG)  \
                  $(LAB3_CC_INFERRED_FLAGS)  \
                  $(LAB3_LINKER_SCRIPT_FLAG) $(LAB3_CC_DEBUG_FLAG) $(LAB3_CC_PROFILE_FLAG) 
